package edu.ufsc.ontology;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sun May 07 17:49:55 BRT 2017 by senhorinha
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Asphalt
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ASPHALT.<p>
     * 
     */
    public static final OWLClass CLASS_ASPHALT = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Asphalt"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Ball
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BALL.<p>
     * 
     */
    public static final OWLClass CLASS_BALL = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Ball"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Bicycle
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BICYCLE.<p>
     * 
     */
    public static final OWLClass CLASS_BICYCLE = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Bicycle"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Cement
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_CEMENT = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Cement"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Clay
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CLAY.<p>
     * 
     */
    public static final OWLClass CLASS_CLAY = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Clay"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Equipament
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class EQUIPAMENT.<p>
     * 
     */
    public static final OWLClass CLASS_EQUIPAMENT = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Equipament"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Grass
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GRASS.<p>
     * 
     */
    public static final OWLClass CLASS_GRASS = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Grass"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Ground
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GROUND.<p>
     * 
     */
    public static final OWLClass CLASS_GROUND = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Ground"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Player
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PLAYER.<p>
     * 
     */
    public static final OWLClass CLASS_PLAYER = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Player"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Raquet
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RAQUET.<p>
     * 
     */
    public static final OWLClass CLASS_RAQUET = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Raquet"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Sport
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SPORT.<p>
     * 
     */
    public static final OWLClass CLASS_SPORT = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Sport"));

    /* ***************************************************
     * Class http://www.co-ode.org/ontologies/pizza/pizza.owl#Water
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class WATER.<p>
     * 
     */
    public static final OWLClass CLASS_WATER = factory.getOWLClass(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#Water"));

    /* ***************************************************
     * Class urn:absolute:sport-ontology#Trunks
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TRUNKS.<p>
     * 
     */
    public static final OWLClass CLASS_TRUNKS = factory.getOWLClass(IRI.create("urn:absolute:sport-ontology#Trunks"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/pizza/pizza.owl#hasEquipament
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASEQUIPAMENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASEQUIPAMENT = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#hasEquipament"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/pizza/pizza.owl#hasFamous
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASFAMOUS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASFAMOUS = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#hasFamous"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/pizza/pizza.owl#isPlayedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPLAYEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPLAYEDBY = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#isPlayedBy"));

    /* ***************************************************
     * Object Property http://www.co-ode.org/ontologies/pizza/pizza.owl#isPlayerOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPLAYEROF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPLAYEROF = factory.getOWLObjectProperty(IRI.create("http://www.co-ode.org/ontologies/pizza/pizza.owl#isPlayerOf"));

    /* ***************************************************
     * Object Property http://www.w3.org/2002/07/owl#topObjectProperty
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property OWL:TOPOBJECTPROPERTY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_OWL:TOPOBJECTPROPERTY = factory.getOWLObjectProperty(IRI.create("http://www.w3.org/2002/07/owl#topObjectProperty"));

    /* ***************************************************
     * Object Property urn:absolute:sport-ontology#isNotPlayedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISNOTPLAYEDIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISNOTPLAYEDIN = factory.getOWLObjectProperty(IRI.create("urn:absolute:sport-ontology#isNotPlayedIn"));

    /* ***************************************************
     * Object Property urn:absolute:sport-ontology#isPlayedIn
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPLAYEDIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPLAYEDIN = factory.getOWLObjectProperty(IRI.create("urn:absolute:sport-ontology#isPlayedIn"));

    /* ***************************************************
     * Object Property urn:absolute:sport-ontology#notHasEquipament
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property NOTHASEQUIPAMENT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_NOTHASEQUIPAMENT = factory.getOWLObjectProperty(IRI.create("urn:absolute:sport-ontology#notHasEquipament"));


}
