package edu.ufsc.ontology.impl;

import edu.ufsc.ontology.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultPlayer <br>
 * @version generated on Sun May 07 17:49:55 BRT 2017 by senhorinha
 */
public class DefaultPlayer extends WrappedIndividualImpl implements Player {

    public DefaultPlayer(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
