package edu.ufsc.ontology.impl;

import edu.ufsc.ontology.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultGrass <br>
 * @version generated on Sat May 06 13:13:06 BRT 2017 by tonussi
 */
public class DefaultGrass extends WrappedIndividualImpl implements Grass {

    public DefaultGrass(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
